services:
  frontend:
    build:
      context: ./mein-react-template
    container_name: carosserie-oerlikon
    restart: unless-stopped
    ports:
      - "5174:80"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  carosserie_mysql_data:
    driver: local